### ISSUE TITLE
ASS instear SRT

### ISSUE THREAD

**Issue by xsoft** [machinewrapped/gpt-subtrans#102]
Hi, would it be possible to allow also other subtitle formats, like .ass?
Thanks

**Comment by machinewrapped** [comment]
Hi, there are no plans to support other subtitle formats at the moment as the program uses the Python srt library extensively for loading, saving and managing subtitles. 

It's possible there is a library that offers a similar level of functionality for multiple subtitle formats and a permissive license, but it's not a priority for me at the moment. It would be a good task for somebody to investigate if they want to contribute to the project though!

**Comment by machinewrapped** [comment]
May look at this in future, but no current plans to support other formats.

**Comment by qgustavor** [comment]
Until it doesn't get implemented I guess one can write a script to convert ASS (or other formats) using Subtitle Edit (it does support a lot of formats and it can be automated) to SRT then back.

The only issue I see is formatting: ASS to SRT conversion is often lossy (simple tags are converted to HTML tags, complex tags are removed), so an alternative for people wanting to keep formatting would be converting ASS to a middle step SRT format for translation with complex replaced by placeholders and a separate file holding those tags to be inserted back in the translation when converting the translated SRT back to ASS.

Can I implement that? Well, I did, on an old project of mine. I stored tags in a JSON file. To make things more efficient tags at he start and end of the lines (which are really common) were completely removed from the SRT, so the model doesn't need to translate them. Lines with way too many tags (often effects like rainbows or other complex typesetting) had all tags stripped and added back on regular intervals (otherwise the model would fail to translate because of the placeholders separating characters). I just not plan making it open-source as this project is too messy, but I just wanted to share this idea anyway.
