### ISSUE TITLE
Documentation/README gemini cli also needs to speficy with -m

### ISSUE THREAD

**Issue by xpufx** [machinewrapped/gpt-subtrans#132]
Testing gemini-subtrans.py I noticed that it errors our with "Model None" and its help includes a model parameter -m. Through some trial and error and looking at the JSON file I learned that the model name format is  -m "Gemini 1.0 Pro" . The current documentation lists -m as an openai only parameter.

**Comment by machinewrapped** [comment]
Thanks - well spotted! I've updated the readme to mention the Gemini-specific parameters (Just API Key and Model).

You've also reminded me that there was a default model when OpenAI was the only provider - I will add provider-specific defaults so that there is a valid model even if it isn't set via command line.

**Comment by machinewrapped** [comment]
I've updated the release with default parameters for gpt-subtrans (gpt-3.5-turbo-0125) and gemini-subtrans (Gemini 1.0 Pro).
https://github.com/machinewrapped/gpt-subtrans/releases/tag/v0.6.1

(Just download and unzip again)
