### ISSUE TITLE
Upload translated subtitles to OpenSubtitles etc.?

### ISSUE THREAD

**Issue by IlmariKu** [machinewrapped/gpt-subtrans#146]
I was wondering, when we are translating the subtitles, I feel like we should help our brothers and sisters, by adding support of uploading the translated subtitles into some public service, where they can be downloaded. I've been doing this manually, but would like to do it more automatically and just spread the love.

It could be by adding this library https://github.com/agonzalezro/python-opensubtitles/tree/master or by some other pattern. But, what do you think, does it make sense?

**Comment by machinewrapped** [comment]
Good idea! I'll look into it. 

I usually run a "fix common errors" in SubtitleEdit and then watch the film with them making any corrections that are needed (there are always some) before uploading them. I'd like to add more automated corrections, e.g. adding line breaks, and improve validation & retranslation so that they are closer to being "finished" when they're translated.

**Comment by IlmariKu** [comment]
Yeah, I've been thinking that matter and that line in the documentation "It is highly recommended to use Subtitle Edit's (https://www.nikse.dk/subtitleedit) "Fix Common Errors" to clean up the translated subtitles (e.g. to add line breaks).".

I haven't stumbled into errors yet, but I also can't download the software (I'm on Mac). Is there any way we could programmatically do this? It would seems just, parsing and validating.

**Comment by machinewrapped** [comment]
The main reason I haven't attempted it yet is that SubtitleEdit does a good job and has years of development behind it, so it makes sense to leverage their efforts.

I'm currently running a custom local build of SubtitleEdit that splits long lines at more natural breaks though, so building that into gpt-subtrans would make sense - and that's the main thing that tends to need fixing since LLMs generally have perfect spelling, grammar and punctuation.

The other common issue that needs fixing is splitting/merging/correcting dialogue based on who is speaking, but I can't think of a way to do that without actually watching the movie yet :-)

**Comment by IlmariKu** [comment]
I'll close this one, since it's not really relevant to anything.
