### ISSUE TITLE
Application Crashes

### ISSUE THREAD

**Issue by fenixpsicologia** [machinewrapped/gpt-subtrans#182]
When all the lines are selected and then "Translate Section" is clicked, the application simply closes.

**Comment by machinewrapped** [comment]
Need more information:

- which provider and model?
- how many lines/scenes/batches?
- what do you have max_threads set to?

It looks like it might be one of those issues where it works fine running from source but crashes in the packaged build.

Try selecting all with Ctrl + A rather than selecting the lines (Ctrl + A selects all the scenes, which should produce the same end result).

You can also try [v0.8.1](https://github.com/machinewrapped/gpt-subtrans/releases/tag/v0.8.1). It contains a very minor fix that should be completely unrelated, but also an update to the openai module - I haven't been able to reproduce the problem in the build so far.

If you still get the error it would help if you can send me the project file.

**Comment by fenixpsicologia** [comment]
> Need more information:
> 
>     * which provider and model?
> 
>     * how many lines/scenes/batches?
> 
>     * what do you have max_threads set to?
> 
> 
> It looks like it might be one of those issues where it works fine running from source but crashes in the packaged build.
> 
> Try selecting all with Ctrl + A rather than selecting the lines (Ctrl + A selects all the scenes, which should produce the same end result).
> 
> You can also try [v0.8.1](https://github.com/machinewrapped/gpt-subtrans/releases/tag/v0.8.1). It contains a very minor fix that should be completely unrelated, but also an update to the openai module - I haven't been able to reproduce the problem in the build so far.
> 
> If you still get the error it would help if you can send me the project file.

I did as you said, and it seems to be working now.
