### ISSUE TITLE
v0.2.2 Unable to save translated subtitles

### ISSUE THREAD

**Issue by AChangAZha** [machinewrapped/gpt-subtrans#28]
Follow up [https://github.com/machinewrapped/gpt-subtrans/issues/27#issuecomment-1564719824](https://github.com/machinewrapped/gpt-subtrans/issues/27#issuecomment-1564719824)
I tried to clear all the project options before translating, but the result was that the program crashed after the translation was completed.
If I use v0.1.9, the subtitle file is saved fine.
[Here is my subtitle file](https://r1kn-my.sharepoint.com/:u:/g/personal/dauzy_r1kn_onmicrosoft_com/EQe-HiSEX1NJg-7v6OzjnpUBckKCyL_pWxQTVfvSFo0z4g?e=VVihX5). It have timestamped. I checked it roughly with SubtitleEdit, this should be a normal subtitle file.

**Comment by machinewrapped** [comment]
Thanks for providing the subtitle file, that was enormously helpful. I would probably never have figured out what the problem was without them!

It turns out the issue was that the first line starts at exactly 0:00:00:000, and thanks to Python's loose type system it was getting converted to "None" when writing the SRT file.

Fixed in the latest release (0.2.3). Please verify the fix and close the issue :-)

**Comment by machinewrapped** [comment]
By the way, the translation seems to be OK when I test it except it output the opening lyrics in English. You _might_ get better results by translating the 'prompt' field in the project GPT Settings to Simplified Chinese. 

The [for movie] and [to language] tags in the prompt are replaced with the movie name and target language automatically, so those should be left as English - though if you want to write a custom prompt without tags that would work too.

**Comment by AChangAZha** [comment]
Thanks for fixing it! It works fine now!

**Comment by AChangAZha** [comment]
@machinewrapped The desyncs problem has indeed been greatly improved!
As you said, some batches are translated into English. 
In addition, there are occasional crashes during the translation process (this problem was also encountered in v0.1.x). The window will close suddenly and the translated content will be lost. I think there may be some unexpected exceptions not being handled. 
Maybe I should try to use the CLI, at least I might be able to see the error message.

**Comment by AChangAZha** [comment]
Sorry, but I still want to ask a question.
`--substitution` sometimes doesn't work. Some words are not replaced. Does it directly replace the words in the original subtitles with the target words, and then send the modified sentences to GPT?

**Comment by machinewrapped** [comment]
Hi, I think the process terminations are caused by a concurrency issue when using Qt's QMutex and Python's built-in mutex - they don't seem to play together nicely. With no error messages it's hard to debug, but I restructured the code to reduce how long locks are held for and stability improved a lot.

If you're using the CLI the issue shouldn't arise since it only uses built-in mutexes... actually it runs single-threaded so even those aren't doing much. If you're using the GUI then... be a little cautious about interacting with it whilst a translation job is running.
