### ISSUE TITLE
Can you code more APIs?

### ISSUE THREAD

**Issue by namdx999** [machinewrapped/gpt-subtrans#70]
Can you code more APIs and use them at the same time? 1 API my speed is a bit slow

**Comment by machinewrapped** [comment]
If you use the "Fast Forward" button in the toolbar it will launch multiple translation threads in parallel, one for each scene up to whatever the maximum count is in the settings. 

If you're using a full OpenAI account this typically delivers better than 4x speed because one or two long scenes will usually be the bottleneck and the rest of the scenes will all have been translated by the time they're done.

If you're on a free OpenAI trial the number of threads is limited to 1 by default, for the simple reason that the rate limits are so strict on the free plan that trying to make multiple requests will almost certainly just result in throttling.

See the issue before this one for an idea about using multiple api keys to get around that - I have no idea if it will work.
