### ISSUE TITLE
Need AutoSave Feature

### ISSUE THREAD

**Issue by xuyuji9000** [machinewrapped/gpt-subtrans#74]
Need AutoSave feature, for example do an automatic save of the translation result every minute or every 10 minutes.

During long running jobs, even when the computer accidentally shuts down, there is minimal translation result lost.

I'm building a manual saving, from time to time, habit to mitigate the risk of losing translation result.

**Comment by machinewrapped** [comment]
It currently auto-saves after each scene translation completes, assuming you have the Auto-Save option checked (it's on by default).

If all the subtitles are in one scene, consider setting a lower scene threshold to divide them up, so that the file will get saved at intervals - if the source is something like a TED Talk there might not be any gaps of more than 5-10 seconds.

It did autosave after every batch originally, but there were some issues that caused intermittent crashes (sometimes corrupting the file, so if anything it made things worse). I could try reintroducing it as an option, it might be more stable now that some GUI/Qt issues have been fixed.

**Comment by machinewrapped** [comment]
Closing this as done, since you can enable autosave after each scene. I experimented with a periodic background save but deemed it too risky since it might be mid-modification and corrupt the project file.
